### ISSUE TITLE
Build failed when bash > 5.2

### ISSUE THREAD

**Issue by gipsyh** [stanford-centaur/pono#318] opened 2023-12-17 04:53 UTC
Maybe should update smt-switch version

https://github.com/cvc5/cvc5/blob/86fe72f6d25023387dbc76be9a6c97d4d27e41d3/src/expr/mkmetakind#L19

**Comment by CyanoKobalamyne** [comment] 2024-01-11 19:50
What is the error you are getting? Could you paste the commands you executed and the error output?

**Comment by CyanoKobalamyne** [comment] 2024-02-06 00:47
It seems that the issue is when running `contrib/setup-smt-switch.sh`:

```
pono/deps/smt-switch/deps/cvc5/src/expr/node_manager_template.h:0: error: undefined replacement ${metakind_mkConstDelete}
pono/deps/smt-switch/deps/cvc5/src/expr/metakind_template.cpp:0: error: undefined replacement ${metakind_constantMaps}
```

**Comment by CyanoKobalamyne** [comment] 2024-02-07 08:19
I will make a PR to update the `smt-switch` version once https://github.com/stanford-centaur/smt-switch/pull/345 is merged, which is needed to fix another build error.

**Closed** 2024-03-07 06:58 UTC
